package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.23 13:16:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsallistujaTest {



  // Generated by ComTest BEGIN
  /** testOsallistuja16 */
  @Test
  public void testOsallistuja16() {    // Osallistuja: 16
    Osallistuja aa = new Osallistuja(); 
    aa.parse(" 1| Hopo| Hessu| 030201-111C|katuos 1|00001 Hopola|0400111222|hessu@hopo.fi"); 
    assertEquals("From: Osallistuja line: 19", "Hopo Hessu", aa.getNimi()); 
    assertEquals("From: Osallistuja line: 20", "Hessu", aa.getEtunimi()); 
    assertEquals("From: Osallistuja line: 21", "Hopo", aa.getSukunimi()); 
    assertEquals("From: Osallistuja line: 22", "030201-111C", aa.getHetu()); 
    assertEquals("From: Osallistuja line: 23", "katuos 1", aa.getKatuosoite()); 
    assertEquals("From: Osallistuja line: 24", "00001 Hopola", aa.getPostiosoite()); 
    assertEquals("From: Osallistuja line: 25", "0400111222", aa.getPuhelin()); 
    assertEquals("From: Osallistuja line: 26", "hessu@hopo.fi", aa.getEmail()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi109 */
  @Test
  public void testRekisteroi109() {    // Osallistuja: 109
    Osallistuja aku1 = new Osallistuja(); 
    assertEquals("From: Osallistuja line: 111", 0, aku1.getId()); 
    aku1.rekisteroi(); 
    Osallistuja aku2 = new Osallistuja(); 
    aku2.rekisteroi(); 
    assertEquals("From: Osallistuja line: 115", 1, aku2.getId() - aku1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetHetu190 */
  @Test
  public void testSetHetu190() {    // Osallistuja: 190
    Osallistuja aku = new Osallistuja(); 
    assertEquals("From: Osallistuja line: 192", "Liian suuri päivämäärä", aku.setHetu("401150")); 
    assertEquals("From: Osallistuja line: 193", "Liian pieni päivämäärä", aku.setHetu("001088")); 
    assertEquals("From: Osallistuja line: 194", "Yksilöosa liian lyhyt", aku.setHetu("121288-1")); 
    assertEquals("From: Osallistuja line: 195", null, aku.setHetu("311212-2317")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse286 */
  @Test
  public void testParse286() {    // Osallistuja: 286
    Osallistuja os = new Osallistuja(); 
    os.parse("  2 | Ankka | Aku | 010101-111D | Akukatu 1 | 11111 Alinna | 099111222 | aku@alinna"); 
    assertEquals("From: Osallistuja line: 289", 2, os.getId()); 
    assertEquals("From: Osallistuja line: 290", "2| Ankka| Aku| 010101-111D| Akukatu 1| 11111 Alinna| 099111222| aku@alinna", os.toString()); 
  } // Generated by ComTest END
}