package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.24 19:34:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsallistumisetWorkshoppeihinTest {



  // Generated by ComTest BEGIN
  /** testOsallistumisetWorkshoppeihin21 */
  @Test
  public void testOsallistumisetWorkshoppeihin21() {    // OsallistumisetWorkshoppeihin: 21
    OsallistumisetWorkshoppeihin osws = new OsallistumisetWorkshoppeihin(); 
    OsallistuuWorkshoppiin o1 = new OsallistuuWorkshoppiin(); 
    OsallistuuWorkshoppiin o2 = new OsallistuuWorkshoppiin(); 
    OsallistuuWorkshoppiin o3 = new OsallistuuWorkshoppiin(); 
    o1.parse("1|1|1"); 
    o2.parse("2|1|2"); 
    o3.parse("3|2|1"); 
    osws.lisaaOsWs(o1); 
    osws.lisaaOsWs(o2); 
    osws.lisaaOsWs(o3); 
    assertEquals("From: OsallistumisetWorkshoppeihin line: 32", o3, osws.anna(2)); 
  } // Generated by ComTest END
}