package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.02 12:22:58 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsallistujaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi96 */
  @Test
  public void testRekisteroi96() {    // Osallistuja: 96
    Osallistuja aku1 = new Osallistuja(); 
    assertEquals("From: Osallistuja line: 98", 0, aku1.getId()); 
    aku1.rekisteroi(); 
    Osallistuja aku2 = new Osallistuja(); 
    aku2.rekisteroi(); 
    assertEquals("From: Osallistuja line: 102", 1, aku2.getId() - aku1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse132 */
  @Test
  public void testParse132() {    // Osallistuja: 132
    Osallistuja os = new Osallistuja(); 
    os.parse("  2 | Ankka | Aku | 010101-111D | Akukatu 1 | 11111 Alinna | 099111222 | aku@alinna"); 
    assertEquals("From: Osallistuja line: 135", 2, os.getId()); 
    assertEquals("From: Osallistuja line: 136", "2| Ankka| Aku| 010101-111D| Akukatu 1| 11111 Alinna| 099111222| aku@alinna", os.toString()); 
  } // Generated by ComTest END
}