package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.07.12 10:09:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsallistujaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi78 */
  @Test
  public void testRekisteroi78() {    // Osallistuja: 78
    Osallistuja aku1 = new Osallistuja(); 
    assertEquals("From: Osallistuja line: 80", 0, aku1.getId()); 
    aku1.rekisteroi(); 
    Osallistuja aku2 = new Osallistuja(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getId(); 
    int n2 = aku2.getId(); 
    assertEquals("From: Osallistuja line: 86", n2-1, n1); 
  } // Generated by ComTest END
}