package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.24 20:16:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class WorkshopTest {



  // Generated by ComTest BEGIN
  /** testWorkshop14 */
  @Test
  public void testWorkshop14() {    // Workshop: 14
    Workshop wo = new Workshop(); 
    wo.parse(" 3 |  kailotus | verstas   | 5| Arvo Naakka| 2 | 12.12.2022| 14:30"); 
    assertEquals("From: Workshop line: 17", 3, wo.getId()); 
    assertEquals("From: Workshop line: 18", "kailotus", wo.getNimi()); 
    assertEquals("From: Workshop line: 19", "verstas", wo.getSijainti()); 
    assertEquals("From: Workshop line: 20", "5", wo.getMaxOs()); 
    assertEquals("From: Workshop line: 21", "Arvo Naakka", wo.getOhjaaja()); 
    assertEquals("From: Workshop line: 22", "12.12.2022", wo.getPvm()); 
    assertEquals("From: Workshop line: 23", "14:30", wo.getKlo()); 
    assertEquals("From: Workshop line: 24", "3| kailotus| verstas| 5| Arvo Naakka| 2| 12.12.2022| 14:30", wo.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi85 */
  @Test
  public void testRekisteroi85() {    // Workshop: 85
    Workshop w1 = new Workshop(); 
    Workshop w2 = new Workshop(); 
    w1.rekisteroi(); 
    w2.rekisteroi(); 
    assertEquals("From: Workshop line: 90", 1, w2.getId() - w1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse250 */
  @Test
  public void testParse250() {    // Workshop: 250
    Workshop ws = new Workshop(); 
    ws.parse(" 3 |  kailotus | verstas   | 5| Arvo Naakka| 2 | 12.12.2022| 14:30"); 
    assertEquals("From: Workshop line: 253", 3, ws.getId()); 
    assertEquals("From: Workshop line: 254", "3| kailotus| verstas| 5| Arvo Naakka| 2| 12.12.2022| 14:30", ws.toString()); 
  } // Generated by ComTest END
}