package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.02 12:34:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class WorkshopTest {



  // Generated by ComTest BEGIN
  /** testParse107 */
  @Test
  public void testParse107() {    // Workshop: 107
    Workshop ws = new Workshop(); 
    ws.parse(" 3 |  kailotus | verstas   | 5| Arvo Naakka"); 
    assertEquals("From: Workshop line: 110", 3, ws.getId()); 
    assertEquals("From: Workshop line: 111", "3| kailotus| verstas| 5| Arvo Naakka", ws.toString()); 
  } // Generated by ComTest END
}