package retriitti.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import retriitti.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.24 19:17:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class WorkshopitTest {



  // Generated by ComTest BEGIN
  /** testLisaa44 */
  @Test
  public void testLisaa44() {    // Workshopit: 44
    Workshopit ws = new Workshopit(); 
    Workshop ws1 = new Workshop(), ws2 = new Workshop(); 
    assertEquals("From: Workshopit line: 47", 0, ws.getLkm()); 
    ws.lisaa(ws1); assertEquals("From: Workshopit line: 48", 1, ws.getLkm()); 
    ws.lisaa(ws2); assertEquals("From: Workshopit line: 49", 2, ws.getLkm()); 
    ws.lisaa(ws1); assertEquals("From: Workshopit line: 50", 3, ws.getLkm()); 
    assertEquals("From: Workshopit line: 51", ws1, ws.anna(0)); 
    assertEquals("From: Workshopit line: 52", ws2, ws.anna(1)); 
    assertEquals("From: Workshopit line: 53", ws1, ws.anna(2)); 
    assertEquals("From: Workshopit line: 54", false, ws.anna(1) == ws1); 
    assertEquals("From: Workshopit line: 55", true, ws.anna(1) == ws2); 
    try {
    assertEquals("From: Workshopit line: 56", ws1, ws.anna(3)); 
    fail("Workshopit: 56 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    ws.lisaa(ws1); assertEquals("From: Workshopit line: 57", 4, ws.getLkm()); 
    ws.lisaa(ws1); assertEquals("From: Workshopit line: 58", 5, ws.getLkm()); 
    ws.lisaa(ws1); 
  } // Generated by ComTest END
}