package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.SisaltaaTarkistaja.*;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.08.09 15:10:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SisaltaaTarkistajaTest {


  // Generated by ComTest BEGIN
  /** testOnkoVain23 */
  @Test
  public void testOnkoVain23() {    // SisaltaaTarkistaja: 23
    assertEquals("From: SisaltaaTarkistaja line: 24", false, onkoVain("123","12")); 
    assertEquals("From: SisaltaaTarkistaja line: 25", true, onkoVain("123","1234")); 
    assertEquals("From: SisaltaaTarkistaja line: 26", true, onkoVain("","1234")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkista53 */
  @Test
  public void testTarkista53() {    // SisaltaaTarkistaja: 53
    SisaltaaTarkistaja tar = new SisaltaaTarkistaja("123"); 
    assertEquals("From: SisaltaaTarkistaja line: 55", null, tar.tarkista("12")); 
    assertEquals("From: SisaltaaTarkistaja line: 56", "Saa olla vain merkkej: 123", tar.tarkista("14")); 
    assertEquals("From: SisaltaaTarkistaja line: 57", null, tar.tarkista("")); 
  } // Generated by ComTest END
}